import { describe, it, expect } from 'vitest'
import { resolveYarnBerryVersions } from '../../src/lockfiles/yarnBerry'

const FIXTURE = `# This file is generated by running "yarn install" inside your project in a Yarn workspace.
# yarn lockfile v1


__metadata:
  version: 8
  cacheKey: 10c0

"axios@npm:^1.0.0":
  version: 1.7.4
  resolution: "axios@npm:1.7.4"
  checksum: 10c0/abc123
  languageName: node
  linkType: hard

"lodash@npm:^4.17.15, lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/def456
  languageName: node
  linkType: hard

"left-pad@workspace:packages/left-pad":
  version: 0.0.0-use.local
  resolution: "left-pad@workspace:packages/left-pad"
  languageName: unknown
  linkType: soft
`

describe('resolveYarnBerryVersions', () => {
  it('resolves a single-descriptor npm: protocol block', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: 'axios', range: '^1.0.0' }])
    expect(result.get('axios')).toBe('1.7.4')
  })

  it('resolves a multi-descriptor block by exact range match', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: 'lodash', range: '^4.17.21' }])
    expect(result.get('lodash')).toBe('4.17.21')
  })

  it('resolves a different range sharing the same multi-descriptor block', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: 'lodash', range: '^4.17.15' }])
    expect(result.get('lodash')).toBe('4.17.21')
  })

  it('omits a name whose range has no matching npm: descriptor', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: 'lodash', range: '^3.0.0' }])
    expect(result.has('lodash')).toBe(false)
  })

  it('skips a name with an undefined range (no way to disambiguate)', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: 'axios', range: undefined }])
    expect(result.has('axios')).toBe(false)
  })

  it('does not resolve a workspace: protocol descriptor for an npm: range request', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: 'left-pad', range: '^1.0.0' }])
    expect(result.has('left-pad')).toBe(false)
  })

  it('never resolves the __metadata block as if it were a package', () => {
    const result = resolveYarnBerryVersions(FIXTURE, [{ name: '__metadata', range: '8' }])
    expect(result.has('__metadata')).toBe(false)
  })
})
