import { describe, it, expect } from 'vitest'
import { resolveYarnVersions } from '../../src/lockfiles/yarn'

const FIXTURE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"lodash@^4.17.15", "lodash@^4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4//eyISDlrMK/AIWSMBanIrhfrsxrDPD9WwOzcpVDdIC4qKdSchTFq6Sc9m2A==

axios@^1.0.0:
  version "1.7.4"
  resolved "https://registry.yarnpkg.com/axios/-/axios-1.7.4.tgz#uuid"
  integrity sha512-uuid
`

describe('resolveYarnVersions', () => {
  it('resolves a single-descriptor block', () => {
    const result = resolveYarnVersions(FIXTURE, [{ name: 'axios', range: '^1.0.0' }])
    expect(result.get('axios')).toBe('1.7.4')
  })

  it('resolves a multi-descriptor block by exact range match', () => {
    const result = resolveYarnVersions(FIXTURE, [{ name: 'lodash', range: '^4.17.21' }])
    expect(result.get('lodash')).toBe('4.17.21')
  })

  it('resolves a different range sharing the same multi-descriptor block', () => {
    const result = resolveYarnVersions(FIXTURE, [{ name: 'lodash', range: '^4.17.15' }])
    expect(result.get('lodash')).toBe('4.17.21')
  })

  it('omits a name whose range has no matching descriptor', () => {
    const result = resolveYarnVersions(FIXTURE, [{ name: 'lodash', range: '^3.0.0' }])
    expect(result.has('lodash')).toBe(false)
  })

  it('skips a name with an undefined range (no way to disambiguate)', () => {
    const result = resolveYarnVersions(FIXTURE, [{ name: 'axios', range: undefined }])
    expect(result.has('axios')).toBe(false)
  })
})
